name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "42 11 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/386 \
            --label org.label-schema.build-date=$(date -u +"%Y-%m-%d") \
            --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD) \
            --tag ${{ github.repository_owner }}/sleep \
            --tag ${{ github.repository_owner }}/sleep:$(git rev-parse --abbrev-ref HEAD) \
            --tag ${{ github.repository_owner }}/sleep:$(date -u +"%Y-%m-%d") \
            --tag ${{ github.repository_owner }}/sleep:latest \
            --tag ghcr.io/${{ github.repository_owner }}/sleep \
            --tag ghcr.io/${{ github.repository_owner }}/sleep:$(git rev-parse --abbrev-ref HEAD) \
            --tag ghcr.io/${{ github.repository_owner }}/sleep:$(date -u +"%Y-%m-%d") \
            --tag ghcr.io/${{ github.repository_owner }}/sleep:latest \
            --push \
            .
  docker-arch-only:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm/v7
          - arm/v6
          - s390x
          - 386
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        run: |
            docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --label org.label-schema.build-date=$(date -u +"%Y-%m-%d") \
            --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD) \
            --tag ${{ github.repository_owner }}/sleep:$(echo ${{ matrix.arch }} | tr '/' '-') \
            --tag ${{ github.repository_owner }}/sleep:$(echo ${{ matrix.arch }} | tr '/' '-')-$(date -u +"%Y-%m-%d") \
            --tag ghcr.io/${{ github.repository_owner }}/sleep:$(echo ${{ matrix.arch }} | tr '/' '-') \
            --tag ghcr.io/${{ github.repository_owner }}/sleep:$(echo ${{ matrix.arch }} | tr '/' '-')-$(date -u +"%Y-%m-%d") \
            --push \
            .
